apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretBackend.name }}
type: Opaque
data:
  host: {{ .Values.secretBackend.host | b64enc }}
  port: {{ .Values.secretBackend.port | b64enc }}
  username: {{ .Values.secretBackend.username | b64enc }}
  password: {{ .Values.secretBackend.password | b64enc }}
  database: {{ .Values.secretBackend.database | b64enc }}