apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceBackend.name }}
  labels:
    {{ .Values.foodAdvisorApi.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.serviceBackend.type }}
  ports:
    - port: {{ .Values.serviceBackend.ports.port }}
      targetPort: {{ .Values.serviceBackend.ports.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{ .Values.foodAdvisorApi.labels | toYaml | nindent 4 }}