apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceFrontend.name }}
  labels:
    {{ .Values.foodAdvisorClient.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.serviceFrontend.type }}
  ports:
    - port: {{ .Values.serviceFrontend.ports.port }}
      targetPort: {{ .Values.serviceFrontend.ports.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{ .Values.foodAdvisorClient.labels | toYaml | nindent 4 }}